---

- name: Join the instance to the domain
  shell: echo {{ ldap.password }} | sudo realm join -v -U {{ ldap.user }} {{ ldap.ip }} --install=/

- name: Make edits to the sssd.conf file 1/3 - comment out ad_server line
  lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^ad_server'
    line: # ad_server <ip address> 
  notify: restart sssd

- name: Make edits to the sssd.conf file 2/3 - disable storing of password
  lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^krb5_store_password_if_offline'
    line: krb5_store_password_if_offline = False 
  notify: restart sssd

- name: Make edits to the sssd.conf file 3/3 - disable chaching of credentials
  lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^cache_credentials'
    line: cache_credentials = False
  notify: restart sssd

- name: Enable password based login by editing sshd_config file
  lineinfile:
    path: /etc/ssh/sshd_conf
    regexp: '^PasswordAuthentication no'
    line: PasswordAuthentication yes
  notify: restart sshd
