kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zabbix-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
- debug
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-pvc
spec:
  storageClassName: zabbix-gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
spec:
  ports:
  - port: 8980
    targetPort: 80
  selector:
    name: zabbix-web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: db
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: zabbix-db
  selector:
    name: zabbix-db
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    name: zabbix-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-web
  template:
    metadata:
      labels:
        name: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:latest
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
          - name: MYSQL_ROOT_PASSWORD
            value: Alcateldc
          - name: DB_SERVER_HOST
            value: zabbix-db
          - name: ZBX_SERVER_HOST
            value: zabbix-server
          - name: PHP_TZ
            value: America/Toronto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
  labels:
    name: zabbix-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-db
  template:
    metadata:
      labels:
        name: zabbix-db
    spec:
      containers:
        - name: zabbix-db
          image: mysql:5.6
          args:
          - --character-set-server=utf8
          - --collation-server=utf8_bin
          ports:
          - containerPort: 3306
            name: mysql
          env:
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
          - name: MYSQL_DATABASE
            value: zabbix
          - name: MYSQL_ROOT_PASSWORD
            value: Alcateldc
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: zabbix-db-storage
          persistentVolumeClaim:
            claimName: zabbix-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-server
  template:
    metadata:
      labels:
        name: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:latest
          ports:
          - containerPort: 162
            name: snmptrapd
          - containerPort: 10051
            name: zabbix-trapper
          - containerPort: 10052
            name: zabbix-jmx
          env:
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            value: zabbix
          - name: DB_SERVER_HOST
            value: zabbix-db
          - name: MYSQL_DATABASE
            value: zabbix
          - name: MYSQL_ROOT_PASSWORD
            value: Alcateldc
          - name: ZBX_CACHESIZE
            value: 2G
          - name: ZBX_HISTORYCACHESIZE
            value: 512M
          - name: ZBX_TRENDCACHESIZE
            value: 128M
          - name: ZBX_VALUECACHESIZE
            value: 400M
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/New_York