- hosts: <hosts>

  tasks:
  - name:  Delete first 155 characters of /root/.ssh/authorized_keys
    shell: sed -i -r 's/.{155}//' /root/.ssh/authorized_keys
 
  - name: Remove pound key from #PermitRootLogin yes
    replace:
          path: /etc/ssh/sshd_config
          regexp: '(^#PermitRootLogin yes\s)(.*)$'
          replace: 'PermitRootLogin yes'
    
  - name: Restart sshd
    systemd:
          state: restarted
          name:  sshd
 
  - name:  Delete /etc/sysconfig/network-scripts/ifcfg-eth0
    shell: rm -f /etc/sysconfig/network-scripts/ifcfg-eth0
   
  - name: install qemu-kvm libvirt bridge-utils libguestfs-tools libvirt-python firewalld ntp tcpdump bind-utils 
    yum: name=qemu-kvm,libvirt,bridge-utils,libguestfs-tools,libvirt-python,firewalld,ntp,tcpdump,bind-utils state=latest update_cache=yes
 
  - name: Start libvirtd
    systemd:
          state: started
          name: libvirtd
  
  - name: Activate libvirtd
    systemd:
         name: libvirtd
         enabled: yes
         masked: no
   
  - name: Activate ntpd
    systemd:
         name: ntpd
         enabled: yes
         masked: no
   
  - name: Start ntpd
    systemd:
         state: started
         name: ntpd
  
  - name: Activate firewalld
    systemd:
         name: firewalld
         enabled: yes
         masked: no
   
  - name: Start firewalld
    systemd:
         state: started
         name: firewalld 

  - name: Construct Network Script ifcfg-br0
    vars:
       FILE: "/etc/sysconfig/network-scripts/ifcfg-br0"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           BOOTPROTO=static
           DEVICE=br0
           ONBOOT=yes
           IPADDR="192.168.3.1"
           NETMASK="255.255.255.0"
           NM_CONTROLLED="no"
           TYPE="Bridge"
           EOM 
     
  - name: Construct Network Script ifcfg-br1
    vars:
       FILE: "/etc/sysconfig/network-scripts/ifcfg-br1"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           BOOTPROTO=static
           DEVICE=br1
           ONBOOT=yes
           IPADDR="192.168.103.1"
           NETMASK="255.255.255.0"
           NM_CONTROLLED="no"
           TYPE="Bridge"
           EOM
     
  - name: Construct Network Script enp4s0
    vars:
       FILE: "/etc/sysconfig/network-scripts/ifcfg-enp4s0"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           BOOTPROTO=static
           DEVICE=enp4s0
           ONBOOT=yes
           IPADDR="10.0.3.10"
           NETMASK="255.255.255.0"
           GATEWAY="10.0.3.1"
           NM_CONTROLLED="no"
           TYPE="Ethernet"
           EOM 
     
  - name: Construct Network Script ifcfg-ens1
    vars:
       FILE: "/etc/sysconfig/network-scripts/ifcfg-ens1"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           BOOTPROTO=static
           DEVICE=ens1
           ONBOOT=yes
           IPADDR="10.100.3.10"
           NETMASK="255.255.255.0"
           GATEWAY="10.100.3.1"
           NM_CONTROLLED="no"
           TYPE="Ethernet"
           EOM
     
  - name: Display message
    debug:
           msg: Add route for jump box
    
  - pause:
           seconds: 2    
     
  - name: Construct Network Script route-enp4s0
    vars:
       FILE: "/etc/sysconfig/network-scripts/route-enp4s0"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           10.0.1.0/24 via 10.0.3.1
           10.0.2.0/24 via 10.0.3.1
           192.168.1.0/24 via 10.0.3.1
           192.168.2.0/24 via 10.0.3.1
           169.254.169.123 via 10.0.3.1
           10.100.1.100 via 10.0.3.1
           EOM

  - name: Display message
    debug:
           msg: Add route for jump box
    
  - pause:
           seconds: 2
     
  - name: Add 2 control to /etc/iproute2/rt_tables
    lineinfile:
           path: /etc/iproute2/rt_tables  
           line:  '2 control'
     
  - name: Construct Network Script route-ens1
    vars:
       FILE: "/etc/sysconfig/network-scripts/route-ens1"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           10.100.3.0 dev ens1 table control
           default via 10.100.3.1 table control
           EOM
     
  - name: Construct Network Script rule-ens1
    vars:
       FILE: "/etc/sysconfig/network-scripts/rule-ens1"
    shell:
       cmd: |
           cat <<EOM > {{FILE}}
           from 10.100.3.0/24 lookup control
           from 192.168.103.0/24 lookup control
           EOM
     
  - name: GATEWAYDEV=enp4s0 to /etc/sysconfig/network
    lineinfile:
           path: /etc/sysconfig/network  
           line:  'GATEWAYDEV=enp4s0'
     
  - name: service
    service:
           name:  network
           state: restarted
     
  - name:  Firewall cmd 1
    shell: firewall-cmd --zone=public --remove-interface=br0
 
  - name:  Firewall cmd 2
    shell: firewall-cmd --zone=public --remove-interface=br1
 
  - name:  Firewall cmd 3
    shell: firewall-cmd --zone=public --remove-interface=enp4s0
 
  - name:  Firewall cmd 4
    shell: firewall-cmd --zone=public --remove-interface=ens1
 
  - name:  Firewall cmd 5
    shell: firewall-cmd --zone=trusted --add-interface=br0 --permanent
 
  - name:  Firewall cmd 6
    shell: firewall-cmd --zone=trusted --add-interface=enp4s0 --permanent
 
  - name:  Firewall cmd 7
    shell: firewall-cmd --zone=trusted --add-interface=br1 --permanent
 
  - name:  Firewall cmd 8
    shell: firewall-cmd --zone=trusted --add-interface=ens1 --permanent
 
  - name:  Firewall cmd 9
    shell: firewall-cmd --reload
 
  - name:  Firewall cmd 10
    shell: firewall-cmd --zone=trusted --list-all
 
  - name: Add net.ipv4.ip_forward = 1  to /etc/sysctl.conf
    lineinfile:
         path: /etc/sysctl.conf
         line:  'net.ipv4.ip_forward = 1'
   
  - name:  Get values from sysctl.conf
    shell: sysctl -p /etc/sysctl.conf

