---  
# The following tasks handle assigning sudoer permissions for users as required

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^zabbix'
    line: 'zabbix ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true