---
# Configure Static IP for Webfilter Interface eth0

- name: Configure ifcfg-eth0 file from template
  template:
    owner: root
    group: root
    mode: 644
    src: ifcfg-eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
  notify: 
    - restart network
