---
# Copy any generic script files required for the haproxy server

- name: Create the script directory if it does not exist
  file:
    path: /home/scripts/license_check
    state: directory
    mode: '0755'

- name: Copy license_check script to portal  
  copy: 
    owner: root  
    group: root 
    mode: '0755'    
    src: license_check.py
    dest: /home/scripts/license_check/license_check.py
