apiVersion: v1
kind: Service
metadata:
  name: graylog-ingest
spec:
  type: LoadBalancer
  selector:
    app: graylog-ingest
  ports:
    - name: elasticsearch
      port: 9350
      targetPort: 9350
    - name: syslog
      port: 514
      targetPort: 514
    - name: plaintext
      port: 5555
      targetPort: 5555
    - name: sidecar-collector
      port: 5044
      targetPort: 5044
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-web
spec:
  type: LoadBalancer
  selector:
    app: graylog-web
  ports:
    - name: web
      port: 9000
      targetPort: 9000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog-ingest
  labels:
    app: graylog-ingest
spec:
  template:
    metadata:
      labels:
        app: graylog-ingest
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:2.5
          env:
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb/graylog
            - name : GRAYLOG_PASSWORD_SECRET
              value: "U9Nv1TUdx5uCOkjL2LkEOGAuJEHmxvf8PTpeUJZF4OkI61I3suQGtNlRFs22RIBFYlL7RrPAMWqlZMCzMr4ABmdGSkvoZI8v"
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "c6f7a8ee93a92d6ee0e3cdc700a7ffd3bb481cd74817a5828f90d16f8eaf7a68"
            - name: GRAYLOG_WEB_ENDPOINT_URI
              value: "http://graylog:9000/api/"
            - name: GRAYLOG_IS_MASTER
              value: "true"
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: "http://es-master-0.elasticsearch-master:9200,http://es-master-1.elasticsearch-master:9200,http://es-master-2.elasticsearch-master:9200"
#            - name: GRAYLOG_CONTENT_PACKS_AUTO_LOAD
#              value: "grok-patterns.json,udp-input-graylog.json"
          ports:
            - containerPort: 5555
            - containerPort: 514
            - containerPort: 5044
#          volumeMounts:
#            - name: content-packs
#              mountPath: /usr/share/graylog/data/contentpacks
#      volumes:
#        - name: content-packs
#          emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog-web
  labels:
    app: graylog-web
spec:
  template:
    metadata:
      labels:
        app: graylog-web
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:2.5
          env:
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb/graylog
            - name : GRAYLOG_PASSWORD_SECRET
              value: "U9Nv1TUdx5uCOkjL2LkEOGAuJEHmxvf8PTpeUJZF4OkI61I3suQGtNlRFs22RIBFYlL7RrPAMWqlZMCzMr4ABmdGSkvoZI8v"
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: "c6f7a8ee93a92d6ee0e3cdc700a7ffd3bb481cd74817a5828f90d16f8eaf7a68"
            - name: GRAYLOG_WEB_ENDPOINT_URI
              value: "http://graylog:9000/api/"
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: "http://es-master-0.elasticsearch-master:9200,http://es-master-1.elasticsearch-master:9200,http://es-master-2.elasticsearch-master:9200"
            - name: GRAYLOG_IS_MASTER
              value: "false"
#            - name: GRAYLOG_CONTENT_PACKS_AUTO_LOAD
#              value: "grok-patterns.json,udp-input-graylog.json"
          ports:
            - containerPort: 9000
#          volumeMounts:
#            - name: content-packs
#              mountPath: /usr/share/graylog/data/contentpacks
#      volumes:
#        - name: content-packs
#          emptyDir: {}
